### ISSUE TITLE
Cannot call method 'filter' of undefined

### ISSUE THREAD

**Issue by ynachiket** [virgo-agent-toolkit/rackspace-monitoring.js#2]
In the current implementation when i try to run the example I get the error:

TypeError: Cannot call method 'filter' of undefined
    at /Users/nachikettorwekar/repo/virgodisposable/rackspace-monitoring.js/index.js:28:45
    at Request._callback (/Users/nachikettorwekar/repo/virgodisposable/rackspace-monitoring.js/lib/identity.js:98:5)
    at Request.self.callback (/Users/nachikettorwekar/repo/virgodisposable/rackspace-monitoring.js/node_modules/request/request.js:123:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/nachikettorwekar/repo/virgodisposable/rackspace-monitoring.js/node_modules/request/request.js:1047:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/nachikettorwekar/repo/virgodisposable/rackspace-monitoring.js/node_modules/request/request.js:998:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

This is the agentTokenList Object  at line 27 : 
{ type: 'unauthorizedError',
  code: 401,
  message: 'forbidden',
  details: 'Invalid or expired authentication token',
  txnId: '.rh-Gors.h-ord1-maas-prod-api1.r-SfbIsEgO.c-30950255.ts-1409038651372.v-baeaaa2' }

**Comment by bravelittlescientist** [comment]
Thanks for the report! Can you confirm that you replaced the credentials in config.js with your own?

**Comment by ynachiket** [comment]
Yes. I did. I am pushing another PR for this. See if that helps fixing the issue.

**Comment by bravelittlescientist** [comment]
Thanks! I'll run it first thing in the A.M. :)
